### 1.8晨测
- 书写一个class继承（带注释）
    class Person {
        //构造器函数。直接给实例化对象扩展属性和方法
        //只要使用new调用了Person 则constructor函数直接调用
        constructor(name, age) {
            this.name = name;
            this.age = age;
        }

        //给实例化对象扩展原型方法
        do() {
            console.log("写代码");
        }
    }


    class Teacher extends Person {
        constructor(sex, name, age) {
            //ES6中继承的子类中，如果使用构造函数constructor()那么就必须使用super()方法初始化，这样下面才可以调用this关键字。
            //super()只能用在子类的构造函数之中，用在其他地方就会报错,这是因为子类自己的this对象，必须先通过父类的构造函数完成塑造，得到与父类同样的实例属性和方法，然后再对其进行加工，加上子类自己的实例属性和方法。
            super(name, age);
            this.sex = sex
        }
        eat() {
            console.log("吃")
        }
    }

- 手写iterator
    function Iterator() {
        //定义一个计数器
        let count = 0;
        return {
            next() {
                if (count < arr.length) {
                    return {
                        value: arr[count++],
                        done: false
                    }
                }
                return {
                    value: undefined,
                    done: true
                }

            }
        }
    }


- 谈一谈generator,及案例说明
    - Generator 函数是 ES6 提供的一种异步编程解决方案，内部封装了很多的状态，被称作状态机 生成器
    - 执行Generator会返回一个迭代器对象（iterator），使用iterator来遍历出Generator内部的状态
    - 形式上，Generator 函数是一个普通函数，但是有两个特征。一是，function关键字与函数名之间有一个星号；二是，函数体内部使用yield表达式，定义不同的内部状态
    - generator代码内部不会马上执行，需要调用next方法的时候才会执行

    function* gen() {
        //必须有next方法调用 才能第一次执行
        console.log("a");
        console.log("b");
        yield console.log("c");
        yield console.log("d");
        yield console.log("e");
    }
    const it = gen();
    console.log(it)
    it.next()
    it.next()
    it.next()
    it.next()

- 谈一谈promise
    - 什么是promise 
        - Promise对象是一个异步编程的解决方案，可以将异步操作以同步的流程表达出来, 避免了层层嵌套的回调函数(俗称'回调地狱')

        - Promise上有 all allSettled race  any reject resolve等静态方法
        - Promise原型对象上有 then catch finally3个方法
    
    - promise的书写
        - Promise是一个构造函数 需要实例化调用
        - Promise对象实例化的时候接收一个参数 是一个函数
        - Promise的参数函数 有两个参数分别是resolve和reject

    - promise返回值
        - Promise实例化会有一个返回值，是一个promise对象，promise对象中有两个值，一个是[PromiseState]:promise的状态，另一个是[[PromiseResult]]:promise返回后的结果

    - promise对象的三种状态
        - 当promise没有返回成功或失败的时候，promise将一直都是pending状态（正在进行中），pending状态的promise不会继续向下执行
        - resolved/fulfilled 成功状态，当在promise中调用了resolve函数，则promise就会返回成功状态，代表当前代码执行成功
        - rejected 失败状态，当promise中调用了reject函数，则返回失败状态的promise，一般异步执行失败的时候使用
        - 当Promise实例化内部抛出错误的时候，代码停止运行，可能不会执行resolve或reject,promise的返回值就仍然是pending

    - PromiseResult的值
        - 当状态是pending的时候，或者resolve和reject函数调用的时候，没有传递任何值，则promise的值一直是undefined
        - resolve和reject调用的时候 传入的参数，则这个参数就是prmiseResult的值
    
- 谈一谈then catch finally
    - Promise的原型对象上有三个方法 then catch finally
        - then 当promise对象返回一个成功状态，则会执行then方法
        - catch 当promise对象返回一个失败状态，则会执行catch方法
        - finally 无论promise但会的是成功还是失败，都会执行finally
        - then catch函数的参数都是一个函数，函数的参数就是调用then的promise对象的promiseResult的值

    - then返回值：
        - then默认返回一个fulfilled成功状态的promise对象,值为undefined
        - 当then的返回值不是一个promise对象的时候，then仍然是 fulfilled 状态，promiseResult的值就是then中return的值
        - 当then返回的是一个promise对象的时候，则then的返回值就是这个promise对象
        - 当then中出现了报错，则then直接返回一个失败的promise对象，并且promiseResult的值就是报错信息

    - catch:
        - 当成功的promise调用了catch，catch内部不会执行 ，而是直接返回原来的promise对象
        - 其他情况下catch的返回值和then类似

    - finally:
        - 当无论成功或失败都要执行一个操作的时候，则需要使用finally，一般finally书写在最后
        - 不接收参数 一般不考虑返回值
